### ISSUE TITLE
NGDC backup

### ISSUE THREAD

**Issue by ocefpaf** [ioos/secoora#116]
@rsignell-usgs suggested:

> Write a little script for [pycsw](http://pycsw.org/) to grab all the iso metadata from the NGDC Collection [Source List](http://www.ngdc.noaa.gov/geoportal/csw?request=getCapabilities&service=csw). We could update every night via cron and thus have pycsw's csw service as a backup.

**Comment by ocefpaf** [comment]
The http://catalog.ioos.us/ URL is a nice web interface to search for data/services.

@rsignell-usgs is there an IOOS csw alternative to NGDC as well?

**Comment by rsignell-usgs** [comment]
We could do what I did for NATO:
* use Kyle's python thredds crawler to extract iso records from thredds info WAFs
* harvest the WAF data into pycsw
* search pycsw using CSW

**Comment by ocefpaf** [comment]
Yes please!  Do you have a recipe for me to follow or an example to point me to?

**Comment by rsignell-usgs** [comment]
@ocefpaf , okay, I put the comt pycsw scripts at:
https://github.com/rsignell-usgs/comt_pycsw

Here's an example of doing a CSW request to this pycsw:
http://nbviewer.ipython.org/gist/rsignell-usgs/58f80172a77b8182843f

Feel free to submit pull requests that add more THREDDS catalogs.

**Comment by ocefpaf** [comment]
Thanks!  I will work on this during the weekend.

**Comment by rsignell-usgs** [comment]
@ocefpaf , I have updated my notebook to show how the bounding box should be specified:
http://nbviewer.ipython.org/gist/rsignell-usgs/58f80172a77b8182843f

Here we specify not only the bounding box, but what coordinate system we are using in the bounding box specification.  To do this, we need to use owslib 0.8.12 (or higher).   I discovered that owslib is no longer in our conda-recipes, and the versions provided elsewhere on binstar are old, so I built/installed the latest using:
```
conda skeleton pypi owslib
conda build owslib
conda install owslib
```
so you should be able to just `conda install -c rsignell owslib`.

**Comment by ocefpaf** [comment]
Our owslib is inside the `conda-recipes-scitools` submodule.  The version they are using is pinned to `0.8.7`  which was OK for my use until now (my scripts did not work with owslib > 0.8.9, but that is resolved now.)

Maybe the submodule was not a good idea...  Do you want me to revert it and update the packages?

**Comment by rsignell-usgs** [comment]
Yeah, I think that probably is a good idea.   I like being in control of our packages.  :grinning:

**Comment by ocefpaf** [comment]
Wait for the PRs...

**Comment by rsignell-usgs** [comment]
@ocefpaf, I scraped the thredds urls from <https://www.ngdc.noaa.gov/docucomp/collectionSource/list?recordSetId=&search=List+Collection+Sources&serviceStatus=APPROVED&serviceType=THREDDS&serviceUrl=&componentId=&max=10000> and added them to the list, then removed some crappy ones like NERACOOS WW3 and a bunch of CDIP catalogs that were not aggregations.   But I was bad.  I did not submit a PR (in fact, I added them using the github "edit" tab!)

**Comment by ocefpaf** [comment]
Thanks @rsignell-usgs.

BTW @vembus mentioned that someone is doing this for SECOORA THREDDS URLs, and he will put us in touch.

PS: :+1: on your idea of a version controled csv (https://github.com/rsignell-usgs/comt_pycsw/issues/1)
