### ISSUE TITLE
CBOFS seems to be `ocean_s_coordinate` and not `ocean_s_coordinate_g1`

### ISSUE THREAD

**Issue by ocefpaf** [ioos/secoora#117]
The metadata in the URL below says `ocean_s_coordinate_g1`.  I am no expert but  and I think it should be `ocean_s_coordinate`:

[http://opendap.co-ops.nos.noaa.gov/thredds/dodsC/CBOFS/fmrc/Aggregated_7_day_CBOFS_Fields_Forecast_best.ncd.html](http://opendap.co-ops.nos.noaa.gov/thredds/dodsC/CBOFS/fmrc/Aggregated_7_day_CBOFS_Fields_Forecast_best.ncd.html)

@rsignell-usgs  BTW do you have am updated URL for `ocean_s_coordinate_g1` and `ocean_s_coordinate_g2`?  The https://cf-pcmdi.llnl.gov/trac/ticket/93 seems to be down and the CF 1.7 draft do not show them.

**Comment by rsignell-usgs** [comment]
@painter1, indeed the trac web site seems to be down, and as you say, I can find no reference to the `ocean_s_coordinate_g1` and `ocean_s_coordinate_g2` coordinates in the CF 1.7 draft at
http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/build/cf-conventions.html

I searched the CF repo for `ocean_s_coordinate` and it appears there in multiple documents, but I don't know which one we could edit for a pull request, as I don't understand the workflow:
https://github.com/cf-convention/cf-convention.github.io/search?p=2&q=ocean_s_coordinate&utf8=%E2%9C%93

@mattben or @painter1, help?

**Comment by painter1** [comment]
@rsignell-usgs and @ocefpaf ,  over the past year we ran into various hardware and security problems and had to migrate the Trac web site twice.  This new url should be permanent: http://cf-trac.llnl.gov/trac .

Indeed Jonathan Gregory declared Ticket 93 as accepted, but I haven't edited it into the CF 1.7 draft yet.

**Comment by ocefpaf** [comment]
@painter1 Thanks!

@rsignell-usgs What about the fisrt part of the issue? Is [this URL](http://opendap.co-ops.nos.noaa.gov/thredds/dodsC/CBOFS/fmrc/Aggregated_7_day_CBOFS_Fields_Forecast_best.ncd.html) is correctly marked as `ocean_s_coordinate_g1` or it should be `ocean_s_coordinate`?  If that is `ocean_s_coordinate_g1` my iris implementation is wrong!

**Comment by rsignell-usgs** [comment]
@painter1, thanks! 
@matbenn, I would like to help @painter1 by forking the conventions, editing the appropriate file to include Ticket 93, and then submitting a pull request.    Can you point me to the appropriate file to edit?

@ocefpaf, you are correct.  The aggregation is inappropriately overriding the vertical coordinate.  It's clear from a [non-aggregated file](http://opendap.co-ops.nos.noaa.gov/thredds/dodsC/NOAA/CBOFS/MODELS/201501/nos.cbofs.fields.n004.20150102.t00z.nc.html) that the coordinate is `ocean_s_coordinate`.   I'll let NOAA CO-OPS know.

**Comment by ocefpaf** [comment]
> The aggregation is inappropriately overriding the vertical coordinate. It's clear from a non-aggregated file that the coordinate is ocean_s_coordinate. I'll let NOAA CO-OPS know.

Thanks.  I got scared for a moment there :stuck_out_tongue_winking_eye: I thought I made a boo-boo with iris vertical coordinates!

**Comment by painter1** [comment]
@rsignell-usgs , thanks for volunteering.  I don't know whether this will work, but we can only find out by trying.

The main file to edit is the DocBook file "appendix-d.xml".  Changes also have to be summarized in the-book-info.xml.  And there may need to be a corresponding change in conformance document; I've not studied Ticket 93 so I don't know.  Note that there is a mandatory system for marking the old and new text in the document; both are kept essentially forever (because all changes are provisional).

Building the html and pdf files from the DocBook files involves running a makefile, which requires some software to be installed.  I don't remember the details but have them written down someplace.

**Comment by rsignell-usgs** [comment]
CO-OPS fixed the catalog and restarted, and looks like
http://opendap.co-ops.nos.noaa.gov/thredds/dodsC/CBOFS/fmrc/Aggregated_7_day_CBOFS_Fields_Forecast_best.ncd.html
now has `ocean_s_coordinate`, so closing

**Comment by ocefpaf** [comment]
Just run my SECOORA notebooks with the latest iris checkout +[PR1520](https://github.com/SciTools/iris/pull/1502) and everything worked out nicely!  Now I don't have excuses to attack issue #5.
