### ISSUE TITLE
Cannot read elevatino data from USF FVCOM

### ISSUE THREAD

**Issue by ocefpaf** [ioos/secoora#122]
The problem is describe in this notebook:

http://nbviewer.ipython.org/github/ioos/secoora/blob/master/sandbox/USF_FVCOM.ipynb

@rsignell-usgs Is it possible that the problem is in the aggregation?  I am lost here...

**Comment by ocefpaf** [comment]
OK, I just found out that iris is failing to create the `Auxiliary coordinates` for  longitude and latitude.  Therefor `node` is loaded as anonymous dimensions and iris does not merge that into one cube.

Now I have to find out why that is happening!

**Comment by rsignell-usgs** [comment]
I remember that in the past some piece of code (pyugrid perhaps?) was having a problem when nv (the connectivity array) was real instead of int.  That wouldn't be it, would it?

**Comment by ocefpaf** [comment]
Thanks I will look into it.  This is what I found so far:

http://nbviewer.ipython.org/github/ioos/secoora/blob/19a9a9d2dce1e60aa4cd9f3615b46954cc7d58a3/sandbox/USF_FVCOM.ipynb

**Comment by ocefpaf** [comment]
That's it.  Spend the whole morning on this...  Is this a problem that should be fixed at the data level?  Or did you guys solved it at a software level with pyugrid?

**Comment by rsignell-usgs** [comment]
For what it's worth, this USF FVCOM URL seems to work with your test:
http://comt.sura.org/thredds/dodsC/data/comt_1_archive/inundation_tropical/USF_FVCOM/Hurricane_Ike_2D_final_run_with_waves.html

So perhaps the secret is in [the NcML we used](https://github.com/ioos/comt_1_archive/blob/master/inundation_tropical/USF_FVCOM/Hurricane_Ike_2D_final_run_with_waves/00_dir.ncml)?

**Comment by ocefpaf** [comment]
I see a `type=int` in the NcML:

https://github.com/ioos/comt_1_archive/blob/master/inundation_tropical/USF_FVCOM/Hurricane_Ike_2D_final_run_with_waves/00_dir.ncml#L37-40

**Comment by rsignell-usgs** [comment]
That's just adding the `start_index` attribute.  The connectivity array is still a `real` array.

**Comment by ocefpaf** [comment]
OK.  Got it.

**Comment by ocefpaf** [comment]
pyugrid cannot read that dataset as well.  It searches for the `cf_role: 'mesh_topology' ` and raises: `There are no standard-conforming meshes`

https://github.com/pyugrid/pyugrid/blob/master/pyugrid/read_netcdf.py#L45-46

Both individual files and the aggregation misses that attribute.

**Comment by rsignell-usgs** [comment]
@jcothran sent me the catalog.xml they were using and I made some modifications to split into multiple separate catalogs linked via `catalogRef`, as well as updating the FVCOM NcML.   It looks like the FVCOM aggregation is now working?
http://nbviewer.ipython.org/gist/rsignell-usgs/d9c1e4d26390ad4eab20

**Comment by ocefpaf** [comment]
Thanks a lot @rsignell-usgs.  I am re-running everything here and hopefully USF FVCOM will show up  in the next maps.

**Comment by ocefpaf** [comment]
@rsignell-usgs Excuse me if this is a stupid question, but I know nothing about FVCOM.

Is this right?

http://nbviewer.ipython.org/gist/ocefpaf/80f66778394f854141ef

There several duplicated times.

**Comment by rsignell-usgs** [comment]
Is what right?

**Comment by ocefpaf** [comment]
The duplicate times.  I have 4 2014-11-01 00:00:00 for example:

```python
import numpy as np
from datetime import datetime

time = cube.coord(axis='T')

np.where([date == datetime(2014, 11, 1, 0, 0) for date in time.units.num2date(time.points)])
(array([34115, 34199, 34283, 34367]),)
```
