### ISSUE TITLE
USF FVCOM duplicate times

### ISSUE THREAD

**Issue by ocefpaf** [ioos/secoora#125]
USF FVCOM has duplicate times with different data. 

For example the date 2014-11-1 00:00:00 repeats 4 times

```python
import iris
import numpy as np
from datetime import datetime

url = 'http://crow.marine.usf.edu:8080/thredds/dodsC/FVCOM-Nowcast-Agg.nc'
cube = iris.load_cube('sea_surface_height_above_geoid')

time = cube.coord(axis='T')
print(np.where([date == datetime(2014, 11, 1, 0, 0) for date in time.units.num2date(time.points)]))
```

`(array([34115, 34199, 34283, 34367]),)`

```python
cube[34115, 0].data, cube[34199, 0].data, cube[34283, 0].data, cube[34367, 0].data
```

```python
(array(-0.18299998342990875, dtype=float32),
 array(-0.22190000116825104, dtype=float32),
 array(-0.22190000116825104, dtype=float32),
 array(-0.19489999115467072, dtype=float32))

```

[nbviewer notebook](http://nbviewer.ipython.org/gist/ocefpaf/80f66778394f854141ef)

My workaround so far is to download the data as is and add a post process step to remove the duplicated times but the last one:

```python
df = df.reset_index().drop_duplicates(cols='index', take_last=True).set_index('index')
```

@jcothran and @rsignell-usgs do you have an idea why USF FVCOM has the duplicate times?  Is this normal for FVCOM?

**Comment by rsignell-usgs** [comment]
Hmmm... There are lots of strange jumps backwards in time also, like `09-Dec-2013 12:00:00` is followed by `06-Dec-2013 01:00:00`.

**Comment by ocefpaf** [comment]
Yep...  Do you know that Chinese saying?

"Do not kill the dragon that bothers you or another one bigger and meaner will take its place."

**Comment by rsignell-usgs** [comment]
Ah, I see the problem.    Each day there is a new 3 day forecast, and these are simply being aggregated using:
```
      <aggregation dimName="time" type="joinExisting" recheckEvery="60 min">
        <scan location="/DATA/WFS_FVCOM_Nowcast_Forecast" suffix=".nc" subdirs="false"/>
      </aggregation>
```
So of course every 3 days there will be a leap backwards when these are aggregated.

Usually we use a forecast model run collection aggregation for this type of data, but unfortunately they don't work for unstructured grid data like FVCOM.  ;-(

**Comment by ocefpaf** [comment]
I guess my workaround is OK then.  I get the last one to be concatenated, that should be the "best" available data at that time.  Right?

**Comment by rsignell-usgs** [comment]
Yes.

**Comment by ocefpaf** [comment]
Another dragon killed.  Moving to the next one...
