### ISSUE TITLE
SECOORA models are not found in the NGDC catalog

### ISSUE THREAD

**Issue by ocefpaf** [ioos/secoora#128]
SECOORA models cannot be found in the [NGDC Geoportal](http://www.ngdc.noaa.gov/geoportal/csw) using OWSLib's  `CatalogueServiceWeb`.

The notebook searches for a list of SECOORA models (cell [9]), filtered by a geo bouding box, time range and CF variable standard_name, and then logs if they are found or not (at the end of the notebook):

http://nbviewer.ipython.org/github/ocefpaf/secoora/blob/master/notebooks/elevation/00-generate_page_html.ipynb

Previous logs can be seen here:
http://ocefpaf.github.io/secoora/comparisons/timeseries/elevation/

(SABGOM and USEAST stopped showing up around 2014-10-24)

@jcothran reported that the models are in fact in the catalog, but my notebook cannot find them.

@rsignell-usgs could this be caused by faulty metadata?

**Comment by rsignell-usgs** [comment]
If we take a look at [the sources that NGDC is harvesting from SECOORA](https://www.ngdc.noaa.gov/docucomp/collectionSource/list?recordSetId=2604653&componentId=&serviceType=&serviceStatus=APPROVED&serviceUrl=&search=List+Collection+Sources) we see ISOWAF, SOS, THREDDS and ERDDAP.

For the [THREDDS source being harvested](https://www.ngdc.noaa.gov/docucomp/collectionSource/list?recordSetId=2604653&componentId=&serviceType=THREDDS&serviceStatus=APPROVED&serviceUrl=&search=List+Collection+Sources), only these two are being harvested:
```
http://omgsrv1.meas.ncsu.edu:8080/thredds/catalog/fmrc/sabgom/catalog.xml
http://omgsrv1.meas.ncsu.edu:8080/thredds/catalog/fmrc/us_east/catalog.xml
```
but not the SABGOM archive at:
``` 
http://omgarch1.meas.ncsu.edu:8080/thredds/catalog/fmrc/sabgom/catalog.xml
```
but the latter seems broken anyway (again).

@jcothran , wouldn't it be better to have NGDC stop harvesting THREDDS and instead harvest from a WAF you control for the modeling datasets?

**Comment by ocefpaf** [comment]
If I understood correctly the models at "http://omgsrv1.meas.ncsu.edu:8080" are being harvest, so my OWSLib query should have found find them, corret?

I know they are down now, but I find it weird that I am unable to find them since last October.

**Comment by jcothran** [comment]
@ocefpaf generally I'd say yes on the all WAF approach and that is what I am doing, the other thredds entries were made by @rsignell-usgs - ideally it just gives people the starting point and allows techs to change thredds server catalogs without updating the catalog itself all the time.  The stopping point currently is that either scripts to use the WAF approach don't work or people in practice don't generally take the WAF approach in searching and expect everything explicitly listed.  I'm still a bit nervous about 'removing' duplicate catalog entries that others like Rich have made earlier in case someone has implemented other search scripts,etc around their catalog entries.

**Comment by ocefpaf** [comment]
@jcothran 
> generally I'd say yes on the all WAF approach

See: https://github.com/ioos/secoora/issues/116

**Comment by ocefpaf** [comment]
I am marking this as won't fix and closing.

The notebooks will keep reporting where the data was found (NGDC csw, hardcoded URLs or #116.)
