### ISSUE TITLE
FVCOM model results freezes when loading with iris

### ISSUE THREAD

**Issue by ocefpaf** [ioos/secoora#135]
This is a weird behavior that I am still unable to find the culprit.  Quite often, when I try to read FVCOM model results, iris just hangs.  Here is a snippet that reproduces the problem.

```python
import pytz
from datetime import datetime, timedelta

import iris
from iris.cube import CubeList


def time_coord(cube):
    """Return the variable attached to time axis and rename it to time."""
    try:
        cube.coord(axis='T').rename('time')
    except CoordinateNotFoundError:
        pass
    timevar = cube.coord('time')
    return timevar


def time_near(cube, datetime):
    """Return the nearest index to a `datetime`."""
    timevar = time_coord(cube)
    try:
        time = timevar.units.date2num(datetime)
        idx = timevar.nearest_neighbour_index(time)
    except IndexError:
        idx = -1
    return idx


stop = datetime(2014, 7, 7, 12)
stop = stop.replace(tzinfo=pytz.utc)
start = stop - timedelta(days=7)

bbox = [-87.40, 24.25, -74.70, 36.70]

units = iris.unit.Unit('celsius')

name_list = ['sea_water_temperature',
             'sea_surface_temperature',
             'sea_water_potential_temperature',
             'equivalent_potential_temperature',
             'sea_water_conservative_temperature',
             'pseudo_equivalent_potential_temperature']

url = "http://crow.marine.usf.edu:8080/thredds/dodsC/FVCOM-Nowcast-Agg.nc"
cubes = iris.load_raw(url)

in_list = lambda cube: cube.standard_name in name_list
cubes = CubeList([cube for cube in cubes if in_list(cube)])
cube = cubes.merge_cube()

lat = iris.Constraint(latitude=lambda cell: bbox[1] <= cell < bbox[3])
lon = iris.Constraint(longitude=lambda cell: bbox[0] <= cell <= bbox[2])
cube = cube.extract(lon & lat)

istart = time_near(cube, start)
istop = time_near(cube, stop)
cube = cube[istart:istop, ...]
```

I opened an issue in iris about this problem, but everything worked when iris devs tried it at the time :unamused: https://github.com/SciTools/iris/issues/1323.  I need to investigate more before opening a new one.

For now my solution was to implement a timeout function to allow the script to continue after a while. However, this issues is leaving out some import SECOORA models.

@rsignell-usgs have you ever experienced this before?

**Comment by rsignell-usgs** [comment]
@ocefpaf , I just tried running this test a few times and it worked fine.  Took about 10 seconds to run.

**Comment by ocefpaf** [comment]
You are using iris from the conda channel, correct?  That version fixes https://github.com/SciTools/iris/issues/1287.  My version should have that fix, but since I also incorporate the vertical coordinate stuff I think I broke it again :unamused:

**Comment by rsignell-usgs** [comment]
I'm still using:
```
iris                      1.7.2_DEV_9e1fd13      np18py27_0    rsignell
```
should I upgrade?

**Comment by ocefpaf** [comment]
NO!  At least until we fix this.

**Comment by ocefpaf** [comment]
How about this one?

http://nbviewer.ipython.org/gist/ocefpaf/65ec555f3e345979ecd2

Works for you?

**Comment by ocefpaf** [comment]
I am between a rock and a hard place with this issue.  If I use the latest branch (with ocean vertical coordinates) I cannot load big dataset.  Even if I [cherry-pick](https://github.com/SciTools/iris/pull/1533) the solution from https://github.com/SciTools/iris/pull/1502, iris does not work and throws a MemoryError.  Something is still not constructing the "LazyArray" for the derived coordinate... Still looking...

**Comment by rsignell-usgs** [comment]
@ocefpaf, yes, it works okay for me, though it takes a long time
http://nbviewer.ipython.org/gist/rsignell-usgs/49581ef00bcf7e9e3b34
The first load takes 24 seconds
The 2nd load takes 170 seconds.

**Comment by ocefpaf** [comment]
That eats up all my CPU and hangs.   I will report this issue in the iris repo.

**Comment by ocefpaf** [comment]
There is a fix for this in iris https://github.com/SciTools/iris/pull/1560, just waiting to get merged...
