### ISSUE TITLE
Add the thredds "catalog_platforms" to the  SECOORA  WAF

### ISSUE THREAD

**Issue by ocefpaf** [ioos/secoora#150]
@jcothran  can you please harvest the data from [http://129.252.139.124/thredds/catalog_platforms.html](http://129.252.139.124/thredds/catalog_platforms.html) and add to the SECOORA WAF?

@rsignell-usgs mentioned that SECOORA WAF is picked up every night by NGDC, so this would make these observations discoverable via CSW search.

**Comment by ocefpaf** [comment]
@jcothran is this possible or is it complex and cumbersome?  I have not idea :grimacing: I thought it was just a on/off situation.

**Comment by rsignell-usgs** [comment]
@ocefpaf & @jcothran, here are the SECOORA ISOWAFs that are harvested nightly:

https://www.ngdc.noaa.gov/docucomp/collectionSource/list?recordSetId=2604653&componentId=&serviceType=ISOWAF&serviceStatus=&serviceUrl=&search=List+Collection+Sources

**Comment by ocefpaf** [comment]
Does that mean all the data in those endpoints are discoverable via the NGDC CSW?

BTW: The second last URL: http://neptune.baruch.sc.edu/xenia/waf/usc/platform/ seems to be missing an "s", I think it should be: http://neptune.baruch.sc.edu/xenia/waf/usc/platforms

**Comment by rsignell-usgs** [comment]
@ocefpaf , yipes, that's bad!   
Can you raise this "platform(s)" issue on https://github.com/ioos/registry/issues?

**Comment by ocefpaf** [comment]
Done: https://github.com/ioos/registry/issues/72

**Comment by jcothran** [comment]
@ocefpaf @rsignell-usgs  thanks for the spelling catch/correction on the WAF endpoint, I'll let the issue/correction get resolved via github, but let me know if you need me to confirm in a separate email thread directly with Anna Milan

**Comment by ocefpaf** [comment]
Running the notebooks again I can confirm that this data can be found in the NGDC CSW. 

```text
07:14:24 INFO: http://tds.secoora.org/thredds/dodsC/carocoops.cap2.buoy.nc.html
07:14:24 INFO: http://tds.secoora.org/thredds/dodsC/carocoops.cap2.buoy_archive.nc.html
07:14:24 INFO: http://tds.secoora.org/thredds/dodsC/carocoops.frp2.buoy.nc.html
07:14:24 INFO: http://tds.secoora.org/thredds/dodsC/carocoops.frp2.buoy_archive.nc.html
07:14:24 INFO: http://tds.secoora.org/thredds/dodsC/carocoops.sun2.buoy_archive.nc.html
07:14:24 INFO: http://tds.secoora.org/thredds/dodsC/fau.lobo.1.nc.html
07:14:24 INFO: http://tds.secoora.org/thredds/dodsC/fldep.bingslanding..nc.html
07:14:24 INFO: http://tds.secoora.org/thredds/dodsC/fldep.stlucieinlet..nc.html
07:14:24 INFO: http://tds.secoora.org/thredds/dodsC/fldep.tolomatoriver..nc.html
07:14:24 INFO: http://tds.secoora.org/thredds/dodsC/lbhmc.2ndave.pier.nc.html
07:14:24 INFO: http://tds.secoora.org/thredds/dodsC/lbhmc.apachepier.pier.nc.html
07:14:24 INFO: http://tds.secoora.org/thredds/dodsC/lbhmc.cherrygrove.pier.nc.html
07:14:24 INFO: http://tds.secoora.org/thredds/dodsC/sccf.fortmyers.wq.nc.html
07:14:24 INFO: http://tds.secoora.org/thredds/dodsC/sccf.gulfofmexico.wq.nc.html
07:14:24 INFO: http://tds.secoora.org/thredds/dodsC/sccf.redfishpass.wq.nc.html
07:14:24 INFO: http://tds.secoora.org/thredds/dodsC/sccf.shellpoint.wq.nc.html
07:14:24 INFO: http://tds.secoora.org/thredds/dodsC/sccf.tarponbay.wq.nc.html
07:14:24 INFO: http://tds.secoora.org/thredds/dodsC/usf.c10.mcat.nc.html
07:14:24 INFO: http://tds.secoora.org/thredds/dodsC/usf.shp.ngwlms.nc.html
07:14:24 INFO: http://thredds.axiomalaska.com/thredds/dodsC/Aquarius_V3_SSS_Daily.nc.html
07:14:24 INFO: http://thredds.axiomalaska.com/thredds/dodsC/Aquarius_V3_SSS_Monthly.nc.html
07:14:24 INFO: http://thredds.axiomalaska.com/thredds/dodsC/Aquarius_V3_SSS_Weekly.nc.html
```
