### ISSUE TITLE
Cannot find past data for SABGOM and USEAST

### ISSUE THREAD

**Issue by ocefpaf** [ioos/secoora#151]
I am using the following URLs for SABGOM and USEAST respectively:

http://omgsrv1.meas.ncsu.edu:8080/thredds/dodsC/fmrc/sabgom/SABGOM_Forecast_Model_Run_Collection_best.ncd

http://omgsrv1.meas.ncsu.edu:8080/thredds/dodsC/fmrc/us_east/US_East_Forecast_Model_Run_Collection_best.ncd

But I cannot find data before the dates: 2014-12-21 15:00:00 (for SABGOM) and 2014-12-23 00:00:00 (for USEAST).  Here is a notebook illustrating the issue:

http://nbviewer.ipython.org/urls/gist.githubusercontent.com/ocefpaf/08c5c5fe64dd5d15726f/raw/44c33c9c19340790495c9c237c1ddbcbc249e955/SABGOM_issue.ipynb

That was possible last week!  @rsignell-usgs  and @jcothran Any clue of what might be happening?  Am I using out of date URLs?

**Comment by garcia1968** [comment]
@ocefpaf @rsignell-usgs 

I know the omgsrv1 is keeps only the 'latest' observations, but forget whether it is a 4-week span(which would explain not being able to reach last week's data this week) or longer.

I remember an earlier email thread and could not find it offhand, perhaps Rich knows, but a rolling time-window can be specified in the iso xml metadata tags which I should do (or Rich can do as he's been pushing up the previous SABGOM metadata changes to the NGDC catalog).  I forget the exact location in the document and tags, but that would allow the metadata to better set expectations on the time-window for available data at an endpoint.

Not sure if omgarch1(archival)  server has the data you are looking for, if the data time-window there edges up to or overlaps the near real-time forecast or not.

**Comment by jcothran** [comment]
@ocefpaf @rsignell-usgs

I know the omgsrv1 is keeps only the 'latest' observations, but forget whether it is a 4-week span(which would explain not being able to reach last week's data this week) or longer.

I remember an earlier email thread and could not find it offhand, perhaps Rich knows, but a rolling time-window can be specified in the iso xml metadata tags which I should do (or Rich can do as he's been pushing up the previous SABGOM metadata changes to the NGDC catalog). I forget the exact location in the document and tags, but that would allow the metadata to better set expectations on the time-window for available data at an endpoint.

Not sure if omgarch1(archival) server has the data you are looking for, if the data time-window there edges up to or overlaps the near real-time forecast or not.

**Comment by rsignell-usgs** [comment]
Joe Zambon from NCSU told me last May that "The plan is to host >30 days of data locally on omgsrv1 and move older data once a month to omgarch1"

**Comment by ocefpaf** [comment]
So the weird thing is that it was working for me a while ago...  I will hard-coded both URLs pointing to `omgsrv1 ` and `omgarch1` in the notebook.  Thanks @jcothran and @rsignell-usgs.

**Comment by rsignell-usgs** [comment]
Hmm, how long ago?   More than a few days?  
omgsrv1 is a rolling archive, so the stuff you used to access may have been moved to omgarch1
http://nbviewer.ipython.org/gist/rsignell-usgs/6d7b9b8d0337f282e611

**Comment by ocefpaf** [comment]
I use the Hurricane Arthur event (2014-7-7) as a test run.  So I used that configuration several times since that date!

However, I found the issue: the notebook only hard-code the URLs when the CSW search does not find SECOORA models.  So I checked the logs and found out that, when  SABGOM and USEAST appeared in the CSW search, I got the right URL.  The URL issue surfaced because this morning because the CSW search failed to find the models.

Anyways, that was good to know.  I need to hard-code both the archive and the current ones.  I will leave the issue opened until I change the URLs.

**Comment by ocefpaf** [comment]
@jcothran Do you know if USEAST is also archive?  I cannot find an equivalent URL (`omgarch1`) for it:

[http://omgarch1.meas.ncsu.edu:8080/thredds/dodsC/fmrc/us_east/US_East_Forecast_Model_Run_Collection_best.ncd](http://omgarch1.meas.ncsu.edu:8080/thredds/dodsC/fmrc/us_east/US_East_Forecast_Model_Run_Collection_best.ncd.html) is a 404.

**Comment by jcothran** [comment]
@ocefpaf I do not believe that USEAST is archived, but you can email Ruoying to confirm.

**Comment by ocefpaf** [comment]
Thanks!
