### ISSUE TITLE
Are re-analysis, blended, etc tagged with coverage_content_type: modelResult?

### ISSUE THREAD

**Issue by ocefpaf** [ioos/secoora#165]
The data on http://thredds.axiomalaska.com/thredds/dodsC/G1_SST_GLOBAL.nc.html
is tagged with `coverage_content_type: modelResult`.  I had the idea (or hope :grimacing:) that `modelResult` would be used only for numerical model results.

I am just asking to solve my ignorance (and fix my scripts that searches for numerical models).

**Comment by ocefpaf** [comment]
@rsignell-usgs Is my interpretation of `modelResult` wrong?

**Comment by rsignell-usgs** [comment]
No, you are correct. @kwilcox, can you please fix?

**Comment by ocefpaf** [comment]
Thanks! I am just trying to minimize the false positives in #153.
