### ISSUE TITLE
Is `catalog platforms` down?

### ISSUE THREAD

**Issue by ocefpaf** [ioos/secoora#166]
Hi Jeremy, can you confirm if http://129.252.139.124/thredds/catalog_platforms.html is down?

Thanks!

**Comment by jcothran** [comment]
Hey Filipe,
Yes it is down at the moment, I'll have it back up tomorrow morning.  Sorry if any inconvenience.
Thanks
Jeremy

**Comment by ocefpaf** [comment]
Not a problem.  Thanks for letting me know!

**Comment by ocefpaf** [comment]
@jcothran Thanks for fixing this.  Closing the issue.

**Comment by ocefpaf** [comment]
@jcothran it seems that something is still not "on:"

Error {
    code = 500;
    message = "There are no datasets in the aggregation DatasetCollectionManager{ collectionName='/nc/fit.sispnj.met/fit.sispnj.met*.nc' recheck=30 min 
 dir=/nc/fit.sispnj.met/ filter=WildcardMatchOnPath{wildcard=*fit.sispnj.met*.nc$ regexp=.*fit\.sispnj\.met.*\.nc$}";
};


@rsignell-usgs any clues that might help us here?

**Comment by rsignell-usgs** [comment]
It's telling you it couldn't find any files on disk at:
/nc/fit.sispnj.met/fit.sispnj.met*.nc
Is that really where the files are?
Are the files readable by the user that is running tomcat/thredds?

**Comment by jcothran** [comment]
@ocefpaf fixed now, it's a server reboot condition where the initial mount to the remote files failed - mounted now and working

**Comment by ocefpaf** [comment]
Yep, that is back.  http://www.ngdc.noaa.gov/geoportal/csw, seems to be down now.  Argh!!!!  Not my week.

**Comment by ocefpaf** [comment]
OK. NGDC CSW is back!

**Comment by ocefpaf** [comment]
@jcothran but the problem with the files is back.  If you click the link below you will not get the OPeNDAP link:

http://129.252.139.124/thredds/dodsC/fit.sispnj.met.nc.html

**Comment by jcothran** [comment]
@ocefpaf working again, had a secondary issue with the remote mount on reboot that is fixed now
