### ISSUE TITLE
Is there an "archive" endpoint for  USEAST?

### ISSUE THREAD

**Issue by ocefpaf** [ioos/secoora#173]
@Ruoying, @jcothran and @vembus are USEAST data archive in a similar manner as SABGOM?

**Comment by rsignell-usgs** [comment]
@kwilcox is interested in this too

**Comment by rsignell-usgs** [comment]
https://github.com/ioos/secoora/issues/151

**Comment by ocefpaf** [comment]
I guess people will let us know if they start archiving it.  Closing this.
