### ISSUE TITLE
Is crow.marine.usf.edu down?

### ISSUE THREAD

**Issue by ocefpaf** [ioos/secoora#176]
http://crow.marine.usf.edu:8080/thredds/dodsC/FVCOM-Nowcast-Agg.nc.html seems to be down.

**Comment by rsignell-usgs** [comment]
@jcothran is listed as the contact on https://www.ngdc.noaa.gov/docucomp/collectionSource/list?recordSetId=2604653&componentId=&serviceType=THREDDS&serviceStatus=&serviceUrl=&search=List+Collection+Sources

**Comment by ocefpaf** [comment]
jdonovan@usf.edu:

> It is up now. I guess the system was rebooted recently. Tomcat is not set up to auto-start on reboot. I will have to look into that.
