### ISSUE TITLE
Do not download G1_SST

### ISSUE THREAD

**Issue by ocefpaf** [ioos/secoora#184]
The data on http://thredds.axiomalaska.com/thredds/dodsC/G1_SST_GLOBAL.nc.html
is tagged as `coverage_content_type: modelResult` (as reported in  #165 ).

We need to hard-code am if-clause to pass data, because it is not a model, to reduce the notebook run time and avoid spurious comparisons.

**Comment by rsignell-usgs** [comment]
@kwilcox, or @shane-axiom, can you guys fix this?   
We need this to be fixed for the CMG portal also, to facilitate model-data comparison.
