### ISSUE TITLE
ESTOFS

### ISSUE THREAD

**Issue by ocefpaf** [ioos/secoora#190]
ESTOFS is still found using the catalog search, but the returned URL seems to be down:

[http://geoport-dev.whoi.edu/thredds/dodsC/estofs/atlantic](http://geoport-dev.whoi.edu/thredds/dodsC/estofs/atlantic.html)

@rsignell-usgs any ideas?

**Comment by ocefpaf** [comment]
OK.  ESTOFS is back online and I did not notice.  The logs show that the notebooks are picking it up.

However, the data is not being paired with any station.  I still have an issue somewhere else down the road...

**Comment by rsignell-usgs** [comment]
It's not working even in the inundation notebook?

**Comment by ocefpaf** [comment]
Nope.  I think I know where to problem is.  I will address that later today.

**Comment by rsignell-usgs** [comment]
Is it related to this issue? https://github.com/ocefpaf/boston_light_swim/issues/2

**Comment by ocefpaf** [comment]
Yep.  That is another bug fixed thanks to [boston_light_swim](https://github.com/ocefpaf/boston_light_swim)!

**Comment by ocefpaf** [comment]
See #209

**Comment by rsignell-usgs** [comment]
nice!
