### ISSUE TITLE
Computing vertical coordinates in CF-compliant datasets

### ISSUE THREAD

**Issue by rsignell-usgs** [ioos/secoora#2]
I realized this morning that one significant issue with creating the virtual glider path tool in Python is the calculation of vertical coordinate using the CF convention information.   The NetCDF-Java library does this for us in the Matlab NCTOOLBOX -- we should use Iris to do this computation for us in Python.   But an issue is that all the vertical coordinates have not been added to Iris yet.    

How hard would it be to help the Iris guys out and solve this issue:
https://github.com/SciTools/iris/issues/762

(I know, it's only programming -- do not ask how long)

But I was thinking that since there are some examples of vertical coordinates there, one would think it would be relatively easy to add a few more.

**Comment by ocefpaf** [comment]
PR https://github.com/SciTools/iris/pull/1304 got merged.  Closing this issue.
