### ISSUE TITLE
NGDC catalog is down

### ISSUE THREAD

**Issue by ocefpaf** [ioos/secoora#217]
Waiting for http://www.ngdc.noaa.gov/geoportal/csw to get back online to run this week `fetch_data`.

**Comment by rsignell-usgs** [comment]
@amilan17 or @geoneubie, is this a scheduled downtime?

**Comment by amilan17** [comment]
This is not a scheduled down time. We are troubleshooting it now. ​

Anna
*~~~~~~Metadata Adds Meaning.~~~~~~*
Anna.Milan@noaa.gov, 303-497-5099
NOAA National Centers for Environmental Information
formerly NOAA’s National Geophysical Data Center
http://www.ngdc.noaa.gov/metadata/emma
*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*

**Comment by amilan17** [comment]
Geoportal is back online.
Thanks for your patience.

Anna
*~~~~~~Metadata Adds Meaning.~~~~~~*
Anna.Milan@noaa.gov, 303-497-5099
NOAA National Centers for Environmental Information
formerly NOAA’s National Geophysical Data Center
http://www.ngdc.noaa.gov/metadata/emma
*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*

**Comment by ocefpaf** [comment]
Thanks @amilan17!
