### ISSUE TITLE
HyCOM data disapeared

### ISSUE THREAD

**Issue by ocefpaf** [ioos/secoora#227]
HyCOM model from PACIOOS, http://oos.soest.hawaii.edu/thredds/dodsC/pacioos/hycom/global,  is still found in a catalog search but the data is not there.

See http://nbviewer.ipython.org/gist/ocefpaf/ce7c23b25263050550c0

@rsignell-usgs Any ideas?

**Comment by ocefpaf** [comment]
Fetching that HyCOM URL is flaky.  I won't investigate it further and I will keep the logs as reference for the issue.

**Comment by rsignell-usgs** [comment]
@pacioos?

**Comment by rsignell-usgs** [comment]
@ocefpaf , does the search pick up the HYCOM from oceannomads?

**Comment by ocefpaf** [comment]
Nope.  The only HYCOM the catalogsearch finds is the one from pacioos. (See #199.)

**Comment by pacioos** [comment]
Seems to be working this morning. Perhaps our TDS or the upstream provider
had a temporary outage?
Cheers,
John Maurer, PacIOOS

**Comment by ocefpaf** [comment]
Thanks John Maurer (@pacioos).
