### ISSUE TITLE
Cannot run SECOORA notebooks due to ConnectTimeoutError

### ISSUE THREAD

**Issue by ocefpaf** [ioos/secoora#231]
```python
from pyoos.collectors.coops.coops_sos import CoopsSos

collector = CoopsSos()
```

```
ConnectTimeout: HTTPConnectionPool(host='opendap.co-ops.nos.noaa.gov', port=80):
Max retries exceeded with

url: /ioos-dif-sos/SOS?service=SOS&request=GetCapabilities&acceptVersions=1.0.0

(Caused by ConnectTimeoutError

(<requests.packages.urllib3.connection.HTTPConnection object at 0x7fe5d8c609d0>,
 'Connection to opendap.co-ops.nos.noaa.gov timed out. (connect timeout=30)'))
```

**Comment by rsignell-usgs** [comment]
I just tried this request and it works:

http://opendap.co-ops.nos.noaa.gov/ioos-dif-sos/SOS?service=SOS&request=GetObservation&version=1.0.0&observedProperty=water_surface_height_above_reference_datum&offering=urn:ioos:station:NOAA.NOS.CO-OPS:8454000&responseFormat=text%2Fcsv&eventTime=2015-12-08T00:00:00Z/2015-12-08T23:59:00Z&result=VerticalDatum%3D%3Durn:ogc:def:datum:epsg::5103&unit=Meters

**Comment by ocefpaf** [comment]
Yep.  The service seems to be back online.  I am re-starting the notebooks...
