### ISSUE TITLE
Plotting time-series as folium popups

### ISSUE THREAD

**Issue by ocefpaf** [ioos/secoora#65]
Folium translates to leaflet two types of popups: simple text and vincent plots (via vega).

Vega popups integrate nicely with folium, but do not support NaN and are not interactive.

I am testings two alternatives to vega: mpld3 and static png.  Both have the same disadvantage they are inserted as html (either `img` or `iframe`) in the simple popup.  Folium/leaflet default configuration limits the simple popup `width` resulting in a small plot with parts of its border cropped (`img`) or a slide bar (`iframe`).

I do not know how to change that configuration.  It is probably easy, but the best solution would be for the popup width/height to be a folium optional keyword.

Mpld3 has the advantage of being interactive, and it is extensible via custom plugins.  Also, it can save JSONs that could be parsed, in the same fashion as vega JSONs, and integrated into folium's current syntax.

Here is an example of the three plots:

http://nbviewer.ipython.org/github/ocefpaf/secoora/blob/mpld3/notebooks/sandbox/test_mpld3.ipynb

@birdage You have some experience with folium, right?  What do you think?  Any ideas?

**Comment by ocefpaf** [comment]
@rsignell-usgs this is a test png image from the mpld3 branch, maybe that is useful:

![mpld3](https://cloud.githubusercontent.com/assets/950575/5680576/b9c80dc8-97ed-11e4-9787-f1335f8829ae.png)

**Comment by ocefpaf** [comment]
I will be using folium PR https://github.com/python-visualization/folium/pull/69 (until we have a better solution) to create the plots.  The PR allows to control the `maxWidth` of HTML popups without breaking simple text popups.

[Here](http://nbviewer.ipython.org/github/ioos/secoora/blob/master/notebooks/elevation/00-inundation_secoora.ipynb) is a nbviewer link for the results.

**Comment by rsignell-usgs** [comment]
Yea!  Nice x-axis date labeling:
![1-12-2015 9-55-40 am](https://cloud.githubusercontent.com/assets/1872600/5704630/5770edd8-9a41-11e4-80b7-d39802248597.png)

**Comment by ocefpaf** [comment]
And thanks to D3 they will adapt automatically if zooming in/out.

**Comment by birdage** [comment]
@ocefpaf they are looking good! glad we took it over now!

**Comment by ocefpaf** [comment]
@birdage and we can click twice on the plots as well :wink:

**Comment by birdage** [comment]
@ocefpaf ace......
